### ISSUE TITLE
Creates queue tables in another Schema

### ISSUE THREAD

**Issue by fereshteh-rabet** [blehnen/DotNetWorkQueue#15]
Hello,

I would like to know if there is a way to generate the queue tables in another schema other than dbo. 

Thank you,
Fereshteh

**Comment by blehnen** [comment]
Hi,

At the moment, there is no support for this.  Its something I'll look into adding; the issue would be that all commands and references to tables would have to start including the schema and right now they don't.

**Comment by blehnen** [comment]
Since the queue stores in own configuration in the queue itself, the schema cannot be part of the configuration, as we need to know the schema in order to read the configuration table.

However, the schema could be specified as part of the connection information itself when spinning up the queue.  That feels slightly wrong, but on the other hand, the schema could be considered part of the connection, as it tells the queue 'where' it is.

I'll think about this some more to see if there are other options.

**Comment by fereshteh-rabet** [comment]
Hi, 

Thank you. It would be nice to have this. This will help to separate the queue for multi schema environments

**Comment by blehnen** [comment]
Added in commit e2f30c2f8dc19bb8092aff0a65492d35ba849644 - might be awhile before nuget packages are released, as there are other items I'm going to clean up first.  I will also need to update the docs.

Example:

var schema = "test1";
var settings = new Dictionary<string, string>();
settings.SetSchema(schema); //set via built-in extension method or set key 'SqlSchema' to the schema
var queueConnection = new QueueConnection(queueName, connectionString, settings);

**Comment by fereshteh-rabet** [comment]
Uh perfect, thank you :)

**Comment by blehnen** [comment]
This has been released as version 0.5.0
