### ISSUE TITLE
I've had a couple of questions. Please answer, thank you.

### ISSUE THREAD

**Issue by cncap** [blehnen/DotNetWorkQueue#3]
1, After the consumer initializes the instance, if the REDIS is disconnected, the consumer can not reconnect to the REDIS when the REDIS is reopened.
2, The consumer once Start(), unless the withdrawal process, it has been running, can not find any way to terminate, can you consider joining Stop()?
3. In QueueContainer, only Create has no Remove.   @@How can I remove the created producer or comsumer?

**Comment by blehnen** [comment]
Hi,

1) This is something I will need to look into, as it should re-connect when REDIS is back up.

I'm assuming it can be duplicated by 

1) Create a queue and add work to it
2) Start a consumer
3) Stop redis
4) Re-start redis
5) The consumer will not process any work, even with Redis back up and connectable ?

2) Currently, the only way to stop the queue is to call Dispose() on it.  Are you asking for a Stop() so that you can Start/Stop the same consumer instance ?

3) Disposing the producer/consumer should be all that's required.
