### ISSUE TITLE
Performance of enqueue and dequeue with sqlite

### ISSUE THREAD

**Issue by SrividyaTR** [blehnen/DotNetWorkQueue#4]
Hi,

The performance of en-queuing and de-queuing seems to be very slow as compared to msmq when using sqlite based persistance. Can you pls comment on the same? I can share the results what I observe for the time taken for such enqueue/dequeue if needed.

**Comment by blehnen** [comment]
Hi,

SQLite doesn't support multiple concurrent writing. Since enqueue and dequeue both require writes to the DB, this can affect performance.  You'll get better performance with the SQLite.org driver vs. the Microsoft driver as well.  However, if your targeting dot core or standard, the Microsoft driver is the only option.

Some suggestions:

1) Use a separate DB3 for each queue, if you have multiple queues.
2) Try to use just one producer, if possible.
3) Use the async consumer and just 1 de-queue thread.  You can use multiple processing threads. The de-queue thread will pass the work off to another thread and then look for more items to de-queue.

Async Consumer - https://github.com/blehnen/DotNetWorkQueue/wiki/ConsumerAsync
